// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMas8d6cp4_RumaK8ICRCcsTuTcLQBug',
    appId: '1:895698934336:web:e2804615b31034ba50dda5',
    messagingSenderId: '895698934336',
    projectId: 'dhiwise-task-f2495',
    authDomain: 'dhiwise-task-f2495.firebaseapp.com',
    databaseURL: 'https://dhiwise-task-f2495-default-rtdb.firebaseio.com',
    storageBucket: 'dhiwise-task-f2495.appspot.com',
    measurementId: 'G-B1T7BBJNX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2rZcCbGXcJM9HWTapY2n04SX3JuCH40',
    appId: '1:895698934336:android:d641cb7581ea1c4a50dda5',
    messagingSenderId: '895698934336',
    projectId: 'dhiwise-task-f2495',
    databaseURL: 'https://dhiwise-task-f2495-default-rtdb.firebaseio.com',
    storageBucket: 'dhiwise-task-f2495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrnn8MMJkebahiJP47hDEc2I_XBkfNUFw',
    appId: '1:895698934336:ios:9279c1725ef18dc950dda5',
    messagingSenderId: '895698934336',
    projectId: 'dhiwise-task-f2495',
    databaseURL: 'https://dhiwise-task-f2495-default-rtdb.firebaseio.com',
    storageBucket: 'dhiwise-task-f2495.appspot.com',
    iosBundleId: 'com.example.dhiwiseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrnn8MMJkebahiJP47hDEc2I_XBkfNUFw',
    appId: '1:895698934336:ios:c00eabd174edc90b50dda5',
    messagingSenderId: '895698934336',
    projectId: 'dhiwise-task-f2495',
    databaseURL: 'https://dhiwise-task-f2495-default-rtdb.firebaseio.com',
    storageBucket: 'dhiwise-task-f2495.appspot.com',
    iosBundleId: 'com.example.dhiwiseTask.RunnerTests',
  );
}
